export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
