export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_RESET = "ADD_BOOK_RESET";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";

export const BOOK_UPDATE_REQUEST = "BOOK_UPDATE_REQUEST";
export const BOOK_UPDATE_FAIL = "BOOK_UPDATE_FAIL";
export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS";
export const BOOK_UPDATE_RESET = "BOOK_UPDATE_RESET";

export const BOOK_DELETE_REQUEST = "BOOK_DELETE_REQUEST";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";

export const BOOK_ASSIGNED_REQUEST = "BOOK_ASSIGNED_REQUEST";
export const BOOK_ASSIGNED_FAIL = "BOOK_ASSIGNED_FAIL";
export const BOOK_ASSIGNED_SUCCESS = "BOOK_ASSIGNED_SUCCESS";
export const BOOK_ASSIGNED_RESET = "BOOK_ASSIGNED_RESET";

export const BOOK_RETURN_REQUEST = "BOOK_RETURN_REQUEST";
export const BOOK_RETURN_FAIL = "BOOK_RETURN_FAIL";
export const BOOK_RETURN_SUCCESS = "BOOK_RETURN_SUCCESS";
export const BOOK_RETURN_RESET = "BOOK_RETURN_RESET";

export const BOOK_HISTORY_REQUEST = "BOOK_HISTORY_REQUEST";
export const BOOK_HISTORY_FAIL = "BOOK_HISTORY_FAIL";
export const BOOK_HISTORY_SUCCESS = "BOOK_HISTORY_SUCCESS";
export const BOOK_HISTORY_RESET = "BOOK_HISTORY_RESET";

export const BOOK_COLLECTED_REQUEST = "BOOK_COLLECTED_REQUEST";
export const BOOK_COLLECTED_FAIL = "BOOK_COLLECTED_FAIL";
export const BOOK_COLLECTED_SUCCESS = "BOOK_COLLECTED_SUCCESS";
export const BOOK_COLLECTED_RESET = "BOOK_COLLECTED_RESET";
