# Generated by Django 3.2.8 on 2021-11-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='num_of_book',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
