# Generated by Django 3.2.8 on 2021-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_collectedbooks_returnedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
