# Generated by Django 3.2.8 on 2021-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_books_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('admission_num', models.CharField(max_length=100, unique=True)),
                ('class_detail', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
